spring:
  application:
    name: azure-blob

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

server:
  port: 8990

sas:
  container-name: images
  connection-string: ${connection-string}